/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface Api3OracleInterface extends ethers.utils.Interface {
  functions: {
    "getBeacon(bytes32)": FunctionFragment;
    "getPreviousPrice(bytes32,uint256)": FunctionFragment;
    "getPrice(bytes32)": FunctionFragment;
    "getTwapPrice(bytes32,uint256)": FunctionFragment;
    "isPriceFeedWhitelisted(bytes32)": FunctionFragment;
    "priceFeedMap(bytes32)": FunctionFragment;
    "priceFeedWhitelisted(bytes32)": FunctionFragment;
    "setBeacon(bytes32,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBeacon",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPreviousPrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTwapPrice",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPriceFeedWhitelisted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceFeedMap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceFeedWhitelisted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeacon",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getBeacon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPreviousPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTwapPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPriceFeedWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceFeedMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceFeedWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBeacon", data: BytesLike): Result;

  events: {};
}

export class Api3Oracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Api3OracleInterface;

  functions: {
    getBeacon(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPreviousPrice(
      _priceFeedKey: BytesLike,
      at: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPrice(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTwapPrice(
      _priceFeedKey: BytesLike,
      _intervals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isPriceFeedWhitelisted(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    priceFeedMap(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    priceFeedWhitelisted(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setBeacon(
      _priceFeedKey: BytesLike,
      _beaconId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getBeacon(
    _priceFeedKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getPreviousPrice(
    _priceFeedKey: BytesLike,
    at: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    _priceFeedKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTwapPrice(
    _priceFeedKey: BytesLike,
    _intervals: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isPriceFeedWhitelisted(
    _priceFeedKey: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  priceFeedMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  priceFeedWhitelisted(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setBeacon(
    _priceFeedKey: BytesLike,
    _beaconId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getBeacon(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getPreviousPrice(
      _priceFeedKey: BytesLike,
      at: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTwapPrice(
      _priceFeedKey: BytesLike,
      _intervals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPriceFeedWhitelisted(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    priceFeedMap(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    priceFeedWhitelisted(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setBeacon(
      _priceFeedKey: BytesLike,
      _beaconId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getBeacon(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPreviousPrice(
      _priceFeedKey: BytesLike,
      at: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTwapPrice(
      _priceFeedKey: BytesLike,
      _intervals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPriceFeedWhitelisted(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    priceFeedMap(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    priceFeedWhitelisted(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBeacon(
      _priceFeedKey: BytesLike,
      _beaconId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBeacon(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPreviousPrice(
      _priceFeedKey: BytesLike,
      at: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTwapPrice(
      _priceFeedKey: BytesLike,
      _intervals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPriceFeedWhitelisted(
      _priceFeedKey: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceFeedMap(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceFeedWhitelisted(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBeacon(
      _priceFeedKey: BytesLike,
      _beaconId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
