/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IExchangeWrapperInterface extends ethers.utils.Interface {
  functions: {
    "getInputPrice(address,address,(uint256))": FunctionFragment;
    "getOutputPrice(address,address,(uint256))": FunctionFragment;
    "getSpotPrice(address,address)": FunctionFragment;
    "swapInput(address,address,(uint256),(uint256),(uint256))": FunctionFragment;
    "swapOutput(address,address,(uint256),(uint256),(uint256))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getInputPrice",
    values: [string, string, { d: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutputPrice",
    values: [string, string, { d: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotPrice",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "swapInput",
    values: [
      string,
      string,
      { d: BigNumberish },
      { d: BigNumberish },
      { d: BigNumberish }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOutput",
    values: [
      string,
      string,
      { d: BigNumberish },
      { d: BigNumberish },
      { d: BigNumberish }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getInputPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutputPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpotPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapInput", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapOutput", data: BytesLike): Result;

  events: {};
}

export class IExchangeWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IExchangeWrapperInterface;

  functions: {
    getInputPrice(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { d: BigNumber }]>;

    getOutputPrice(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { d: BigNumber }]>;

    getSpotPrice(
      inputToken: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<[[BigNumber] & { d: BigNumber }]>;

    swapInput(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      minOutputTokenBought: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapOutput(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      maxInputTokeSold: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getInputPrice(
    inputToken: string,
    outputToken: string,
    inputTokenSold: { d: BigNumberish },
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { d: BigNumber }>;

  getOutputPrice(
    inputToken: string,
    outputToken: string,
    outputTokenBought: { d: BigNumberish },
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { d: BigNumber }>;

  getSpotPrice(
    inputToken: string,
    outputToken: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber] & { d: BigNumber }>;

  swapInput(
    inputToken: string,
    outputToken: string,
    inputTokenSold: { d: BigNumberish },
    minOutputTokenBought: { d: BigNumberish },
    maxPrice: { d: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapOutput(
    inputToken: string,
    outputToken: string,
    outputTokenBought: { d: BigNumberish },
    maxInputTokeSold: { d: BigNumberish },
    maxPrice: { d: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getInputPrice(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { d: BigNumber }>;

    getOutputPrice(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { d: BigNumber }>;

    getSpotPrice(
      inputToken: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { d: BigNumber }>;

    swapInput(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      minOutputTokenBought: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { d: BigNumber }>;

    swapOutput(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      maxInputTokeSold: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { d: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    getInputPrice(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOutputPrice(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpotPrice(
      inputToken: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapInput(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      minOutputTokenBought: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapOutput(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      maxInputTokeSold: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getInputPrice(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOutputPrice(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSpotPrice(
      inputToken: string,
      outputToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapInput(
      inputToken: string,
      outputToken: string,
      inputTokenSold: { d: BigNumberish },
      minOutputTokenBought: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapOutput(
      inputToken: string,
      outputToken: string,
      outputTokenBought: { d: BigNumberish },
      maxInputTokeSold: { d: BigNumberish },
      maxPrice: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
