/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IInflationMonitorInterface extends ethers.utils.Interface {
  functions: {
    "appendMintedTokenHistory((uint256))": FunctionFragment;
    "isOverMintThreshold()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "appendMintedTokenHistory",
    values: [{ d: BigNumberish }]
  ): string;
  encodeFunctionData(
    functionFragment: "isOverMintThreshold",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "appendMintedTokenHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOverMintThreshold",
    data: BytesLike
  ): Result;

  events: {};
}

export class IInflationMonitor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IInflationMonitorInterface;

  functions: {
    appendMintedTokenHistory(
      _amount: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isOverMintThreshold(overrides?: CallOverrides): Promise<[boolean]>;
  };

  appendMintedTokenHistory(
    _amount: { d: BigNumberish },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isOverMintThreshold(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    appendMintedTokenHistory(
      _amount: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    isOverMintThreshold(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    appendMintedTokenHistory(
      _amount: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isOverMintThreshold(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    appendMintedTokenHistory(
      _amount: { d: BigNumberish },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isOverMintThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
