/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPerpToken, IPerpTokenInterface } from "../IPerpToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPerpToken__factory {
  static readonly abi = _abi;
  static createInterface(): IPerpTokenInterface {
    return new utils.Interface(_abi) as IPerpTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPerpToken {
    return new Contract(address, _abi, signerOrProvider) as IPerpToken;
  }
}
