/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IStakeModule, IStakeModuleInterface } from "../IStakeModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "staker",
        type: "address",
      },
    ],
    name: "notifyStakeChanged",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStakeModule__factory {
  static readonly abi = _abi;
  static createInterface(): IStakeModuleInterface {
    return new utils.Interface(_abi) as IStakeModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakeModule {
    return new Contract(address, _abi, signerOrProvider) as IStakeModule;
  }
}
